language: node_js
node_js:
- stable
install:
- npm ci
cache:
  directories:
  - "$home/.npm"
  - "node_modules"
  override:
  - npm ci
  - npm run cy:verify
deploy:
  provider: heroku
  api_key:
    secure: sHouhOINlub/1huSvzL1fHlSWBaZ17EeXpIFyux5BcA1gHgSIx72+O8L2gOEoWqY3sirhhDmKjH10oZFKPZkitUXQVpuD88PFkavuRI6dO/r6buPsEvt0kA5WsGPwio2UVeCVo8nWIM+d+2Hirk/xrYUGUi5DCk0DXLeoKU+b1uMc3iDsuTxOxFle20gjqemI5Ghk1s6GSdHP4j1c70bINBmHxyAr0YvMAh+gIqLrcl8ubS0/mhic3sHMF7oEj1PT/9Mc0OT+F16e8ypjKGqbU94mxziyOctCzDgJ9IQW4aypzYuX3PgYPKqhA8K50Gyh2RatlbmSz5w0LWpnF/CYuJ3FWozWIzuV393LVCAxWlTsfGv9XB/nLEGSfLbgbRH+4/094BG/PeMmfgSwKQFeD2UIFOwelZgqccmBRUDozn/393BNbqZ73bN65xopsaCznKiVuSXFqpicoWadO/qa/u4OGvt5jo7yFa7X3XQe7i3nQ8HWYWLmiBYyzSKtJSeZVijbTXch41MayEoa9z/8sZ4uQZ73bvodDGaavCG3Ln0UwYb0E8dUE6byI9rH4uzBDkN6gppZYmxyg09aJf/ze5eoEzVNMiI/5IZCoG/7nHoRqHhB1e/7jnByH4KAFujhQQCVz+ZmOpt7yCfagFS9N4Kj9lxy+Nev4l3bo8sHVo=
  app: 
    master: travis-ci-lb 
    stage: travis-ci-lb-stage
  on:
    repo: bourguy/travis
script:
  # start server in the background
  - npm start -- --silent &
  # run all Cypress tests and record on the dashboard
  - npm run cypress:run -- #--record
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  # this avoids flake in Travis jobs
  - kill $(jobs -p) || true