language: node_js
node_js:
- stable
install:
- npm ci
cache:
  directories:
  - "$home/.npm"
  - node_modules
  override:
  - npm ci
  - npm run cy:verify
deploy:
  provider: heroku
  api_key:
    secure: d6444642-1d30-4109-a817-c9a13ab5dd9e
app: 
    master: travis-ci-lb 
    stage: travis-ci-lb-stage
  on:
    repo: bourguy/travis
script:
- npm start -- --silent &
- npm run cypress:run -- --record --key b7ed0b0e-48dc-4f82-a65c-868d70e372a6
- kill $(jobs -p) || true
