language: node_js
node_js:
- stable
install:
- npm ci
cache:
  directories:
  - "$home/.npm"
deploy:
  provider: heroku
  api_key:
    master: k8gLmmmnnGe9x1NiotL2Vj6iFHC0jJUo+vzVANDnYu9Pzh9Ez6R0HbLf4xhtSBMhR73Kyjzo7wgJKZvDgL1pvVI6DgwXUNpJlRU4gofCKtgMkNvh2tTTHZQuWEDrqE+iRgHgpzLOYpjLtsK1OqECygXFe16bGgIIAOaCsuu8/kHa9Z0JYueHjyyBKFgpmt+XhIHojer5opC7i9H8WHvoUZZzD1TzI/hV0/Ywmhdv3BtpdtQTRy7h1PzuKjDJsU50C8LwQ7j91bi69SimZD6lwkXPKvacExvj2hNGtxdUeY3JAIMds8b0p/IL39xOcoA5axaiePKG1WPmdSJ/DIgSNExkfnJyggGAzA1nRItntlzRdwanwVINcgT0oLsVfj5qLdxS1/+1DflYhfwj95QvJPZk7I+cISNJyuyJGhL2Tp+SB2jP/5SM1kVbswp0ADpbNhedSPDPeP9tMX8FAo/T8Lm2xief7Ps1SBaag8nEXpOM8aUHjoriR57Y8E5m0uBQPvQii4iRmI7kwOfsrA45aLZYHZmpSPF3RX3yUpFuz81tGoiTpcmBPICNsUSjDtj0ykDgJlqFjKZnRnrvo4mBtW38e68fCjbY+Ru1ytvI2e9y5Wvcxdq35qZv2qtRRzNGP72IITzF/CyvptIH2dhl9Gmvj1tPt9dg6aHogjvvLhc=
    stage: wHvea8BnHuwhloD5wyviYMM7aUF5HWQg4uVnxedbfB+3FGMRq9SxDycaH8Npp7Eo0y05cf4KB/TmmNtlU0OQnZYhdLQmXXHvTNkF3rxR6HIsQMoHBxzJ0bYeUAvtM+CQtaFu1DRkui82qkOlRZ4HE4fnz1RDH39XZRMRcHCpJWV467NrmVW7D9pe5Ayp1Ah9ZsjC3vibe6omGbdqjYLh9IbuehFmNgw5NgDKSUpK2+nKrykGmo8APioQV/h70kjdUwmkH51RIyNgC2yikWBw1eHe2l9F4AzJCAbVXhi2yaX/oveGk0lq/EAa8cTiEO6mUktm4CHl+Z2ZSHjBPsy9f1OR6Nz5qAb0+yiysNLMBPaBO2ZpknzlBruBP44hmYptmQfXLvgIssX4GxALGrLBMtzjUe9/YEDC3vwGeToq2Lr+RlpzMu4RS6kWbPVxOGODl9cjqENZD7hI4GxmRxKi3pV/MTN9rLFVWoebPS4xG2ed3UUpVErjfR8GXUmUIU+9ip95KiYQe1++ptroR3sxz+3t/HGhvekxwE6jzQoiu43RHeFSKr597OJk9mW/5a4019Gb9rSrKbyO3kmEvVlwNpv/PJZChZ72qPBphjByrOBnyoiNfxBNjnPuj0oer1zf0Xxs9RN+dph1ZtrhtGbdEut//du2KcslMeVYitr0vs0=
  app: 
    master: travis-ci-lb
    stage: travis-ci-lb-stage
  on:
    repo: bourguy/travis
