language: node_js
node_js:
- stable
install:
- npm ci
cache:
  directories:
  - "$home/.npm"
  - "node_modules"
deploy:
  provider: heroku
  api_key:
    secure: ZR0PjOkx46fxAPIrkBj/4rknXjFtvIjNlTYMOcTccZDOBM9sYQ3EQzADKTXB99c62q5k36IzSuHUc0KiCy3d0z9VJ5bTl2kQrOmyFSsDrjZAYrFTtE1ZWGWkaD9Wbsw4Z7KxPMA4K0BOwC8QjKeF48YT7FunvG9vxZfu8nommd4zCLQlqSpAGGYL/q9ctivmaqSI0d8EnT/yBPML208yQrLVqgrwCArPI0fSC4mVRCrZyvQpCF4YpmsVBtCMsHPuIrIrijgBimggyYGFZhlv3KGClK4u2QxcKsmLM3UetubweQRq3DeXl8NIV+ZfHg+c9NvLvezSQEvdOSXr/2f0SJ/9IihdiFB60UCXFvbygkT4cXbntDlWHWyGlfpYadIUQUEGG8KV8VH5zmD5vucrpi4mRu/wN23JqsmbIVsnMoAK1Mp169V4VX9kdWunDeYp0hT4QlzuALgAjj6EI5DMb+waTwUqe+qpkfRpRVRwUAYWkxz00if1oUrYpSfCgAnbL9be2PSxu8fAlnRkKr31hUpIUrl9saS4MHASKOLvdE22CZKtIr7v5lAKlvlA9tm/uLyJtajcv92OcZyb1xyf9a8YVu2wD+XSg0zQPm9Kpg266hjAjE6utoRVb1NvYUWj+oJZRVru8QXHYa6UYSsZroc4W7R59bLNxT7uKY6iHbU=
  app: 
    master: travis-ci-lb 
    stage: travis-ci-lb-stage
  on:
    repo: bourguy/travis
before_script:
  - $npm run start 
script:
  - $(npm bin)/cypress run --record 

