language: node_js
node_js:
- stable
install:
- npm ci
cache:
  directories:
  - "$home/.npm"
  - "node_modules"
  override:
  - npm ci
  - npm run cy:verify
deploy:
  provider: heroku
  api_key:
    secure: d6444642-1d30-4109-a817-c9a13ab5dd9e
  app: 
    master: travis-ci-lb 
    stage: travis-ci-lb-stage
  on:
    repo: bourguy/travis
script:
  # start server in the background
  - npm start -- --silent &
  # run all Cypress tests and record on the dashboard
  - npm run cypress:run -- #--record
  # after all tests finish running we need
  # to kill all background jobs (like "npm start &")
  # this avoids flake in Travis jobs
  - kill $(jobs -p) || true