language: node_js
node_js:
- stable
install:
- npm ci
cache:
  directories:
  - "$home/.npm"
deploy:
  provider: heroku
    api_key:
    master: k8gLmmmnnGe9x1NiotL2Vj6iFHC0jJUo+vzVANDnYu9Pzh9Ez6R0HbLf4xhtSBMhR73Kyjzo7wgJKZvDgL1pvVI6DgwXUNpJlRU4gofCKtgMkNvh2tTTHZQuWEDrqE+iRgHgpzLOYpjLtsK1OqECygXFe16bGgIIAOaCsuu8/kHa9Z0JYueHjyyBKFgpmt+XhIHojer5opC7i9H8WHvoUZZzD1TzI/hV0/Ywmhdv3BtpdtQTRy7h1PzuKjDJsU50C8LwQ7j91bi69SimZD6lwkXPKvacExvj2hNGtxdUeY3JAIMds8b0p/IL39xOcoA5axaiePKG1WPmdSJ/DIgSNExkfnJyggGAzA1nRItntlzRdwanwVINcgT0oLsVfj5qLdxS1/+1DflYhfwj95QvJPZk7I+cISNJyuyJGhL2Tp+SB2jP/5SM1kVbswp0ADpbNhedSPDPeP9tMX8FAo/T8Lm2xief7Ps1SBaag8nEXpOM8aUHjoriR57Y8E5m0uBQPvQii4iRmI7kwOfsrA45aLZYHZmpSPF3RX3yUpFuz81tGoiTpcmBPICNsUSjDtj0ykDgJlqFjKZnRnrvo4mBtW38e68fCjbY+Ru1ytvI2e9y5Wvcxdq35qZv2qtRRzNGP72IITzF/CyvptIH2dhl9Gmvj1tPt9dg6aHogjvvLhc=
    stage: zVtxQDUYa/Psb8kIK0jiGPA8SR+pdvQNd+/anONr4btpHLCPmUDQ2b2peLmtEH+Iu3VQ0Vipv0gJDhwe1NzzFa+02Bh6jHERgo1pQLBI6Q8SUBiZvB5lMB7/bgsszk5r9MfqXIEhvw/0bCqjD70pwUACuC9/9Asv0aVwgzDW0bmYeJWptdPFhk7x/HOfoszNAFIsGPyUPGtwBHAMXqmhLmWHbHodDV7cOcHnt/59IeHVf2PYhe724hXYYFEMef8YFrujkRUnXwgNlr3jlCSwuaIhSgIJeMZKxv0EGIuzd1GXCb0MeLUyKDEmEHqkru/Q0aW2apDOYjednv4Huf1nPWFwj8ZvHgoEb5Ipyo5A+TlUsRyc3rb0MomsXGpg5Rcpg8EaXb0ZNizTVgCBerAC2bLqCvQ9wNL2b2H8zaCcCMvQIzsTOr+o32esr3tN+XI3nwMcwfVGav2YQajWH6mPNPJGySfTp6mMoFYNiFeqHC8yF7h5Ai7eudDUoOvlLLYXTbeFvXA+f6LR14EzFIldSmNYhKIWOrdwBF6NidpxxQJw/gxB+FEQP8t+ARzTnWCTD4JnSuHIx5wZybU5CT8m/LdiKMzBl9KtSPWX7pr/aave4MHEftvP31vnRin0YE+PotXmDHHIuZqcdDzRlFxmqa4X4I+1HrEzBBYBLlakV/Y=

  app: 
    master: travis-ci-lb
    stage: travis-ci-lb-stage
  on:
    repo: bourguy/travis
 